id = "interactive01"

bind = "0.0.0.0:8005"
grpc_bind = "0.0.0.0:7005"

nexus_addr = "localhost:7001"

activitypub_base_url = "https://api.sn.solsynth.dev/cgi/co/activitypub"

[debug]
database = true
print_routes = false

[security]
internal_public_key = "keys/internal_public_key.pem"
